### ISSUE TITLE
notification can't allowed

### ISSUE THREAD

**Issue by OrangeOC** [d4rken-org/capod#35]
When I update this app to version V2.1.1-rc0, the notifications themselves are no longer allowed.
I'm using Pixel 5a on android 13.
In the FOSS version I can allow notification permissions as usual.

**Comment by d4rken** [comment]
This should have been fixed in `v2.1.1-rc0` via #29.
Are you sure you have the latest version on Google Play? You have to opt-in to beta testing, it's not released to production on Google Play.

![Screenshot_20220922_143329](https://user-images.githubusercontent.com/1439229/191748313-80ffc721-4448-4806-b09e-c2cd56b3ee3c.png)

**Comment by OrangeOC** [comment]
Oh,sorry!
I misunderstood the version.
After running the update, it worked as usual!
