### ISSUE TITLE
Notification disappears if "IGNORE_BATTERY_OPTIMIZATIONS" is not granted

### ISSUE THREAD

**Issue by GitGitro** [d4rken-org/capod#52]
Hi, in the main screen after installing the app it should ask for `Permission.IGNORE_BATTERY_OPTIMIZATION` but it's not listed.
I went through the code but it seems everything is there, so i don't know what's missing

**Comment by d4rken** [comment]
Currently we only ask for this when the monitor mode is `ALWAYS`. Do you think it's needed in other cases too?

https://github.com/d4rken-org/capod/blob/23ec2f025e50c3440c3a87f2e192bcaf729dc339/app-common/src/main/java/eu/darken/capod/main/core/PermissionTool.kt#L37

**Comment by d4rken** [comment]
What device/ROM are you on?
How many seconds are a few? :grin: 
Can you catch this in a logfile?

It's fixed with battery permission or is it fixed when setting monitor mode to "ALWAYS"?

It might be the monitor canceling itself due to not seeing the connected device, but that happens after 15 seconds:

https://github.com/d4rken-org/capod/blob/3d05296eb2f6be9bbdd26acf2d22cbb7a0386551/app/src/main/java/eu/darken/capod/monitor/core/worker/MonitorWorker.kt#L139-L150

If the monitor worker cancels itself, that also dismisses the notification.
I see no issue with requesting the battery optimization permission in other modes, but we need to first understand what is happening.

**Comment by d4rken** [comment]
What device/ROM are you on?
How many seconds are a few? :grin: 
Can you catch this in a logfile?

It's fixed with battery permission or is it fixed when setting monitor mode to "ALWAYS"?

It might be the monitor canceling itself due to not seeing the connected device, but that happens after 15 seconds:

https://github.com/d4rken-org/capod/blob/3d05296eb2f6be9bbdd26acf2d22cbb7a0386551/app/src/main/java/eu/darken/capod/monitor/core/worker/MonitorWorker.kt#L139-L150

If the monitor worker cancels itself, that also dismisses the notification.
I see no issue with requesting the battery optimization permission in other modes, but we need to first understand what is happening.

**Comment by d4rken** [comment]
Do you have a device address selected in settings? If NOT, then I think what happens fits your description, e.g.

```java
Monitor mode: AUTOMATIC
No Pods are connected, canceling worker soon.
PodMonitor.onEach(): null
PodMonitor.onEach(): null
PodMonitor.onEach(): null
PodMonitor.onEach(): null
PodMonitor.onEach(): null
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
PodMonitor.onEach(): AirPodsPro...
Canceling worker now, still no Pods connected.
PodMonitor.onCompletion()
Monitor job quit
Execution finished after 15132ms, Data {}
```

**Comment by d4rken** [comment]
What do you think about #53?

**Comment by d4rken** [comment]
If it happens again, can you record a debug log (Settings>Support)? Or build the app from source and get the log from that?
